version: '3'

volumes:
  web_db:
  auth_db:
  notify_db:
  scrap_db:

services:
  # ===DATABASES===
  web_db:
    image: mysql:8.2
    restart: always
    environment:
      TERM: xterm-256color
    env_file:
     - ./.env.development
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - web_db:/var/lib/mysql

  auth_db:
    image: mysql:8.2
    restart: always
    environment:
      TERM: xterm-256color
    env_file:
     - ./.env.development
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - auth_db:/var/lib/mysql

  notify_db:
    image: mysql:8.2
    restart: always
    environment:
      TERM: xterm-256color
    env_file:
     - ./.env.development
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - notify_db:/var/lib/mysql

  scrap_db:
    image: mysql:8.2
    restart: always
    environment:
      TERM: xterm-256color
    env_file:
     - ./.env.development
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - scrap_db:/var/lib/mysql

  # ===APPS===
  web:
    build: .
    stdin_open: true
    tty: true
    entrypoint: web/config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    depends_on:
     - web_db
    links:
     - web_db
    env_file:
     - ./.env.development
    volumes:
     - .:/home/apps
    ports:
     - '3000:3000'
    expose:
     - '3000'

  auth:
    build: .
    stdin_open: true
    tty: true
    entrypoint: auth/config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    depends_on:
     - auth_db
    links:
     - auth_db
    env_file:
     - ./.env.development
    volumes:
     - .:/home/apps
    ports:
     - '3001:3000'
    expose:
     - '3001'

  notify:
    build: .
    stdin_open: true
    tty: true
    entrypoint: notify/config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    depends_on:
     - notify_db
    links:
     - notify_db
    env_file:
     - ./.env.development
    volumes:
     - .:/home/apps
    ports:
     - '3002:3000'
    expose:
     - '3002'

  scrap:
    build: .
    stdin_open: true
    tty: true
    entrypoint: scrap/config/setup_app.sh
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: America/Fortaleza
      TERM: xterm-256color
    depends_on:
     - scrap_db
    links:
     - scrap_db
    env_file:
     - ./.env.development
    volumes:
     - .:/home/apps
    ports:
     - '3003:3000'
    expose:
     - '3003'


