default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: '<%= ENV['WEB_MYSQL_HOST'] %>'

development:
  <<: *default
  database: <%= ENV["WEB_DEV_DATABASE_NAME"] %>

test:
  <<: *default
  database: <%= ENV["WEB_TEST_DATABASE_NAME"] %>

production:
  <<: *default
  database: <%= ENV["WEB_PROD_DATABASE_NAME"] %>
