default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DEV_DATABASE_NAME"] %>
  url: <%= ENV["DEV_DATABASE_URL"] %><%= ENV["DEV_DATABASE_NAME"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %>
  url: <%= ENV["TEST_DATABASE_URL"] %><%= ENV["TEST_DATABASE_NAME"] %>

production:
  <<: *default
  database: <%= ENV["PROD_DATABASE_NAME"] %>
  username: <%= ENV["PROD_DATABASE_USERNAME"] %>
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>
  url: <%= ENV["PROD_DATABASE_URL"] %><%= ENV["PROD_DATABASE_NAME"] %>
